spring:
  application:
    name: viora-streaming-core
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:viora_streaming_user}
    password: ${SPRING_DATASOURCE_PASSWORD:viora_streaming_password}
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/viora_streaming_db}
    hikari:
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${GRID_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      app: ${GRID_SENDER:dobry9495@gmail.com}
    test-connection: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,trace

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"

jwt:
  key: ${JWT_KEY:YzEyMzR0bXZxQzRmNTZ2cEFoUGVpMWdIajU3aWdoZ2g}
client:
  register-callback-url: ${CLIENT_CALLBACK_URL:http://localhost/movies}
  dropped-callback-url: ${CLIENT_DROPPED_CALLBACK_URL:http://localhost/auth/drop-password}

server:
  port: ${SPRING_APP_PORT:8080}
  host: ${SPRING_APP_HOST:localhost}
