INSERT INTO public.directors (id, name, photo) VALUES (1, 'Jeff Fowler', null);
INSERT INTO public.directors (id, name, photo) VALUES (5, 'Tatsuya Yoshihara', null);
INSERT INTO public.directors (id, name, photo) VALUES (4, 'Corin Hardy', null);
INSERT INTO public.directors (id, name, photo) VALUES (3, 'Christopher Nolan', null);
INSERT INTO public.directors (id, name, photo) VALUES (2, 'James Gunn', null);
INSERT INTO public.directors (id, name, photo) VALUES (6, 'Steven Spielberg', null);
INSERT INTO public.directors (id, name, photo) VALUES (7, 'Brendan Rudnicki', null);
INSERT INTO public.directors (id, name, photo) VALUES (8, 'Tim Miller', null);
INSERT INTO public.directors (id, name, photo) VALUES (9, 'Ridley Scott', null);
INSERT INTO public.directors (id, name, photo) VALUES (10, 'Ric Roman Waugh', null);
INSERT INTO public.directors (id, name, photo) VALUES (11, 'David Lynch', null);
INSERT INTO public.directors (id, name, photo) VALUES (12, 'Gene Gallerano, William Pisciotta', null);
INSERT INTO public.directors (id, name, photo) VALUES (13, 'William Kaufman', null);
INSERT INTO public.directors (id, name, photo) VALUES (14, 'Boris Quercia', null);
INSERT INTO public.directors (id, name, photo) VALUES (15, 'David Gelb', null);
INSERT INTO public.directors (id, name, photo) VALUES (16, 'Tom Harper', null);
INSERT INTO public.directors (id, name, photo) VALUES (17, 'Tyler Perry', null);
INSERT INTO public.directors (id, name, photo) VALUES (18, 'Scott Derrickson', null);
INSERT INTO public.directors (id, name, photo) VALUES (19, 'Sam Raimi', null);
INSERT INTO public.directors (id, name, photo) VALUES (20, 'Dan Trachtenberg', null);
INSERT INTO public.directors (id, name, photo) VALUES (21, 'Ian Tuason', null);
INSERT INTO public.directors (id, name, photo) VALUES (22, 'Denis Villeneuve', null);
INSERT INTO public.directors (id, name, photo) VALUES (23, 'Mike Mitchell, Stephanie Stine', null);
INSERT INTO public.directors (id, name, photo) VALUES (24, 'Lana Wachowski, Lilly Wachowski', null);
INSERT INTO public.directors (id, name, photo) VALUES (26, 'Ron Clements, John Musker, Don Hall', null);
INSERT INTO public.directors (id, name, photo) VALUES (25, 'Andrew Adamson, Vicky Jenson', null);
INSERT INTO public.directors (id, name, photo) VALUES (27, 'Bill Condon', null);
INSERT INTO public.directors (id, name, photo) VALUES (28, 'Woo-Seong Choi', null);
INSERT INTO public.directors (id, name, photo) VALUES (29, 'Kevin Williamson', null);
INSERT INTO public.directors (id, name, photo) VALUES (30, 'Derek Drymon', null);
INSERT INTO public.directors (id, name, photo) VALUES (32, 'Jon Favreau', null);
INSERT INTO public.directors (id, name, photo) VALUES (31, 'Frank Darabont', null);
INSERT INTO public.directors (id, name, photo) VALUES (33, 'Hamish Hamilton, Marcus Liversedge', null);
INSERT INTO public.directors (id, name, photo) VALUES (34, 'Joe Carnahan', null);
INSERT INTO public.directors (id, name, photo) VALUES (35, 'Haruo Sotozaki, Hikaru Kondô', null);
INSERT INTO public.directors (id, name, photo) VALUES (36, 'George Lucas', null);
INSERT INTO public.directors (id, name, photo) VALUES (37, 'Pasquale Festa Campanile', null);
INSERT INTO public.directors (id, name, photo) VALUES (38, 'David Frankel', null);
INSERT INTO public.directors (id, name, photo) VALUES (39, 'Seth MacFarlane', null);
INSERT INTO public.directors (id, name, photo) VALUES (40, 'Maggie Gyllenhaal', null);
INSERT INTO public.directors (id, name, photo) VALUES (41, 'Domee Shi', null);
INSERT INTO public.directors (id, name, photo) VALUES (42, 'Greta Gerwig', null);
INSERT INTO public.directors (id, name, photo) VALUES (43, 'Lee Cronin', null);
INSERT INTO public.directors (id, name, photo) VALUES (44, 'Ryan Coogler', null);
INSERT INTO public.directors (id, name, photo) VALUES (45, 'Jayendra', null);
INSERT INTO public.directors (id, name, photo) VALUES (46, 'John Patton Ford', null);
INSERT INTO public.directors (id, name, photo) VALUES (47, 'Isaac Florentine', null);
INSERT INTO public.directors (id, name, photo) VALUES (48, 'Yu Yang', null);
INSERT INTO public.directors (id, name, photo) VALUES (49, 'Jo-Anne Brechin', null);
INSERT INTO public.directors (id, name, photo) VALUES (50, 'Anthony Russo, Joe Russo', null);
INSERT INTO public.directors (id, name, photo) VALUES (51, 'Karan Johar', null);
INSERT INTO public.directors (id, name, photo) VALUES (52, 'Hugo Cardozo', null);
INSERT INTO public.directors (id, name, photo) VALUES (53, 'Peter Jackson', null);
INSERT INTO public.directors (id, name, photo) VALUES (54, 'Ruben Fleischer', null);
INSERT INTO public.directors (id, name, photo) VALUES (55, 'Anurag Singh', null);
INSERT INTO public.directors (id, name, photo) VALUES (56, 'Kelsey Mann', null);
INSERT INTO public.directors (id, name, photo) VALUES (57, 'Christophe Gans', null);
INSERT INTO public.directors (id, name, photo) VALUES (58, 'Bong Joon Ho', null);
INSERT INTO public.directors (id, name, photo) VALUES (59, 'Emerald Fennell', null);
INSERT INTO public.directors (id, name, photo) VALUES (60, 'B.J. Novak', null);
INSERT INTO public.directors (id, name, photo) VALUES (61, 'Joseph Kosinski', null);
INSERT INTO public.directors (id, name, photo) VALUES (62, 'James Cameron', null);
INSERT INTO public.directors (id, name, photo) VALUES (63, 'Kristoffer Borgli', null);
INSERT INTO public.directors (id, name, photo) VALUES (64, 'Paul Feig', null);
INSERT INTO public.directors (id, name, photo) VALUES (65, 'Yavuz Turgul', null);
INSERT INTO public.directors (id, name, photo) VALUES (66, 'Khalid Fahad', null);
INSERT INTO public.directors (id, name, photo) VALUES (67, 'Phil Lord, Christopher Miller', null);
INSERT INTO public.directors (id, name, photo) VALUES (68, 'Bob Persichetti, Peter Ramsey, Rodney Rothman', null);
INSERT INTO public.directors (id, name, photo) VALUES (69, 'Lisa Steen', null);
INSERT INTO public.directors (id, name, photo) VALUES (70, 'Paul Thomas Anderson', null);
INSERT INTO public.directors (id, name, photo) VALUES (71, 'Byron Howard, Rich Moore, Jared Bush', null);
INSERT INTO public.directors (id, name, photo) VALUES (72, 'Aaron Horvath, Michael Jelenic, Pierre Leduc', null);
INSERT INTO public.directors (id, name, photo) VALUES (73, 'Luis Llosa', null);
INSERT INTO public.directors (id, name, photo) VALUES (74, 'Richard Thorpe', null);
INSERT INTO public.directors (id, name, photo) VALUES (75, 'Stephen Sommers', null);
INSERT INTO public.directors (id, name, photo) VALUES (76, 'Giuseppe Tornatore', null);
INSERT INTO public.directors (id, name, photo) VALUES (77, 'Jeanne Moreau', null);
INSERT INTO public.directors (id, name, photo) VALUES (78, 'Francis Ford Coppola', null);
INSERT INTO public.directors (id, name, photo) VALUES (79, 'Larry Yang', null);
INSERT INTO public.directors (id, name, photo) VALUES (80, 'Chloé Zhao', null);
INSERT INTO public.directors (id, name, photo) VALUES (81, 'Pete Docter, David Silverman, Lee Unkrich', null);
INSERT INTO public.directors (id, name, photo) VALUES (82, 'Chris Renaud, Patrick Delage', null);
INSERT INTO public.directors (id, name, photo) VALUES (83, 'Bryce Wagoner', null);
INSERT INTO public.directors (id, name, photo) VALUES (84, 'Robert Zemeckis', null);
INSERT INTO public.directors (id, name, photo) VALUES (85, 'Castille Landon', null);
INSERT INTO public.directors (id, name, photo) VALUES (86, 'Vanessa Parise', null);
INSERT INTO public.directors (id, name, photo) VALUES (87, 'Joss Whedon', null);
INSERT INTO public.directors (id, name, photo) VALUES (88, 'Daniel Chong', null);
INSERT INTO public.directors (id, name, photo) VALUES (89, 'Meng-Ju Shieh', null);
INSERT INTO public.directors (id, name, photo) VALUES (90, 'Dean DeBlois, Chris Sanders', null);
INSERT INTO public.directors (id, name, photo) VALUES (91, 'Kelly Marcel', null);
INSERT INTO public.directors (id, name, photo) VALUES (93, 'Michael Paul Girard', null);
INSERT INTO public.directors (id, name, photo) VALUES (92, 'Makoto Shinkai', null);
INSERT INTO public.directors (id, name, photo) VALUES (94, 'David G. Derrick Jr., Jason Hand, Dana Ledoux Miller', null);
INSERT INTO public.directors (id, name, photo) VALUES (95, 'Angel Manuel Soto', null);
INSERT INTO public.directors (id, name, photo) VALUES (96, 'Bart Layton', null);
INSERT INTO public.directors (id, name, photo) VALUES (97, 'Mel Gibson', null);
INSERT INTO public.directors (id, name, photo) VALUES (98, 'Christopher McQuarrie', null);
INSERT INTO public.directors (id, name, photo) VALUES (99, 'Gareth Edwards', null);
INSERT INTO public.directors (id, name, photo) VALUES (100, 'Jon M. Chu', null);
INSERT INTO public.directors (id, name, photo) VALUES (101, 'Cemal Alpan', null);
INSERT INTO public.directors (id, name, photo) VALUES (102, 'Jonah Hill', null);
INSERT INTO public.directors (id, name, photo) VALUES (103, 'Jamie Powell', null);
INSERT INTO public.directors (id, name, photo) VALUES (104, 'Paul Michael Glaser', null);
INSERT INTO public.directors (id, name, photo) VALUES (105, 'Jon Watts', null);
INSERT INTO public.directors (id, name, photo) VALUES (107, 'Nora Ephron', null);
INSERT INTO public.directors (id, name, photo) VALUES (106, 'Quentin Tarantino', null);
INSERT INTO public.directors (id, name, photo) VALUES (108, 'Guillermo del Toro', null);
INSERT INTO public.directors (id, name, photo) VALUES (109, 'Nikolay Lebedev', null);
INSERT INTO public.directors (id, name, photo) VALUES (110, 'Chris Sanders', null);
INSERT INTO public.directors (id, name, photo) VALUES (111, 'Hayao Miyazaki', null);
INSERT INTO public.directors (id, name, photo) VALUES (112, 'Renny Harlin', null);
INSERT INTO public.directors (id, name, photo) VALUES (113, 'Rob Cohen', null);
INSERT INTO public.directors (id, name, photo) VALUES (114, 'Patrick Hughes', null);
INSERT INTO public.directors (id, name, photo) VALUES (115, 'John Lasseter', null);
INSERT INTO public.directors (id, name, photo) VALUES (116, 'N/A', null);
INSERT INTO public.directors (id, name, photo) VALUES (117, 'Tyree Dillihay, Adam Rosette', null);
INSERT INTO public.directors (id, name, photo) VALUES (118, 'Phil Cunningham, Brent Dawes', null);
INSERT INTO public.directors (id, name, photo) VALUES (119, 'Gavin Polone', null);
INSERT INTO public.directors (id, name, photo) VALUES (120, 'Johannes Roberts', null);
INSERT INTO public.directors (id, name, photo) VALUES (121, 'Matt Bettinelli-Olpin, Tyler Gillett', null);
INSERT INTO public.directors (id, name, photo) VALUES (122, 'Alan Erlich', null);
INSERT INTO public.directors (id, name, photo) VALUES (123, 'David Fincher', null);
INSERT INTO public.directors (id, name, photo) VALUES (124, 'Chandler Levack', null);
INSERT INTO public.directors (id, name, photo) VALUES (125, 'Vanessa Caswill', null);
INSERT INTO public.directors (id, name, photo) VALUES (126, 'Olivier Ducray, Wilfried Méance', null);
INSERT INTO public.directors (id, name, photo) VALUES (127, 'Chris Appelhans, Maggie Kang', null);
INSERT INTO public.directors (id, name, photo) VALUES (128, 'Henry Selick', null);
INSERT INTO public.directors (id, name, photo) VALUES (129, 'Emma Tammi', null);
INSERT INTO public.directors (id, name, photo) VALUES (130, 'Tommy Wirkola', null);
INSERT INTO public.directors (id, name, photo) VALUES (131, 'Fernando Di Leo', null);
INSERT INTO public.directors (id, name, photo) VALUES (132, 'Michael Chaves', null);
INSERT INTO public.directors (id, name, photo) VALUES (133, 'Bruno Gaburro', null);
INSERT INTO public.directors (id, name, photo) VALUES (134, 'Martin Scorsese', null);
INSERT INTO public.directors (id, name, photo) VALUES (135, 'Timur Bekmambetov', null);
INSERT INTO public.directors (id, name, photo) VALUES (136, 'Jalmari Helander', null);
INSERT INTO public.directors (id, name, photo) VALUES (137, 'Michel Gondry', null);
INSERT INTO public.directors (id, name, photo) VALUES (138, 'Genki Kawamura', null);
INSERT INTO public.directors (id, name, photo) VALUES (139, 'Jared Bush, Byron Howard', null);
INSERT INTO public.directors (id, name, photo) VALUES (140, 'Aditya Dhar', null);
INSERT INTO public.directors (id, name, photo) VALUES (141, 'Nia DaCosta', null);
INSERT INTO public.directors (id, name, photo) VALUES (143, 'Gore Verbinski', null);
INSERT INTO public.directors (id, name, photo) VALUES (142, 'Jared Hess', null);
INSERT INTO public.directors (id, name, photo) VALUES (145, 'Vicky Jewson', null);
INSERT INTO public.directors (id, name, photo) VALUES (144, 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson', null);
INSERT INTO public.directors (id, name, photo) VALUES (146, 'Olivier Nakache, Éric Toledano', null);
