INSERT INTO public.writers (id, name, photo) VALUES (1, 'Owen Egerton', null);
INSERT INTO public.writers (id, name, photo) VALUES (2, 'Pat Casey, Josh Miller, John Whittington', null);
INSERT INTO public.writers (id, name, photo) VALUES (3, 'Thomas Keneally, Steven Zaillian', null);
INSERT INTO public.writers (id, name, photo) VALUES (4, 'N/A', null);
INSERT INTO public.writers (id, name, photo) VALUES (5, 'Rhett Reese, Paul Wernick', null);
INSERT INTO public.writers (id, name, photo) VALUES (6, 'Dan O''Bannon, Ronald Shusett', null);
INSERT INTO public.writers (id, name, photo) VALUES (7, 'Mitchell LaFortune, Chris Sparling', null);
INSERT INTO public.writers (id, name, photo) VALUES (8, 'Frank Herbert, David Lynch', null);
INSERT INTO public.writers (id, name, photo) VALUES (9, 'Gene Gallerano, William Pisciotta', null);
INSERT INTO public.writers (id, name, photo) VALUES (10, 'William Kaufman, Paul Reichelt', null);
INSERT INTO public.writers (id, name, photo) VALUES (11, 'Boris Quercia', null);
INSERT INTO public.writers (id, name, photo) VALUES (12, 'Steven Knight', null);
INSERT INTO public.writers (id, name, photo) VALUES (13, 'Tyler Perry', null);
INSERT INTO public.writers (id, name, photo) VALUES (14, 'Zach Dean', null);
INSERT INTO public.writers (id, name, photo) VALUES (15, 'Damian Shannon, Mark Swift', null);
INSERT INTO public.writers (id, name, photo) VALUES (16, 'Patrick Aison, Dan Trachtenberg, Jim Thomas', null);
INSERT INTO public.writers (id, name, photo) VALUES (17, 'Ian Tuason', null);
INSERT INTO public.writers (id, name, photo) VALUES (18, 'Denis Villeneuve, Jon Spaihts, Frank Herbert', null);
INSERT INTO public.writers (id, name, photo) VALUES (19, 'Lilly Wachowski, Lana Wachowski', null);
INSERT INTO public.writers (id, name, photo) VALUES (20, 'Jonathan Aibel, Glenn Berger, Darren Lemke', null);
INSERT INTO public.writers (id, name, photo) VALUES (21, 'Jared Bush, Ron Clements, John Musker', null);
INSERT INTO public.writers (id, name, photo) VALUES (22, 'William Steig, Ted Elliott, Terry Rossio', null);
INSERT INTO public.writers (id, name, photo) VALUES (23, 'Christopher Nolan, Kai Bird, Martin Sherwin', null);
INSERT INTO public.writers (id, name, photo) VALUES (24, 'Melissa Rosenberg, Stephenie Meyer', null);
INSERT INTO public.writers (id, name, photo) VALUES (25, 'Jonathan Nolan, Christopher Nolan, David S. Goyer', null);
INSERT INTO public.writers (id, name, photo) VALUES (26, 'Kevin Williamson, Guy Busick, James Vanderbilt', null);
INSERT INTO public.writers (id, name, photo) VALUES (27, 'Pam Brady, Matt Lieberman, Marc Ceccarelli', null);
INSERT INTO public.writers (id, name, photo) VALUES (28, 'Mark Fergus, Hawk Ostby, Art Marcum', null);
INSERT INTO public.writers (id, name, photo) VALUES (29, 'Stephen King, Frank Darabont', null);
INSERT INTO public.writers (id, name, photo) VALUES (30, 'Joe Carnahan, Michael McGrale', null);
INSERT INTO public.writers (id, name, photo) VALUES (31, 'Koyoharu Gotouge, Hikaru Kondô', null);
INSERT INTO public.writers (id, name, photo) VALUES (32, 'George Lucas', null);
INSERT INTO public.writers (id, name, photo) VALUES (33, 'Franco Ferrini, Franco Marotta, Enrico Oldoini', null);
INSERT INTO public.writers (id, name, photo) VALUES (34, 'Aline Brosh McKenna, Lauren Weisberger', null);
INSERT INTO public.writers (id, name, photo) VALUES (35, 'Seth MacFarlane, Alec Sulkin, Wellesley Wild', null);
INSERT INTO public.writers (id, name, photo) VALUES (36, 'Maggie Gyllenhaal, Mary Shelley', null);
INSERT INTO public.writers (id, name, photo) VALUES (37, 'Domee Shi, Julia Cho, Sarah Streicher', null);
INSERT INTO public.writers (id, name, photo) VALUES (38, 'Greta Gerwig, Noah Baumbach', null);
INSERT INTO public.writers (id, name, photo) VALUES (39, 'Lee Cronin', null);
INSERT INTO public.writers (id, name, photo) VALUES (40, 'Ryan Coogler', null);
INSERT INTO public.writers (id, name, photo) VALUES (41, 'Umarji Anuradha, A.N. Balakrishnan, Jayendra', null);
INSERT INTO public.writers (id, name, photo) VALUES (42, 'John Patton Ford, Robert Hamer, John Dighton', null);
INSERT INTO public.writers (id, name, photo) VALUES (43, 'Richard Lowry', null);
INSERT INTO public.writers (id, name, photo) VALUES (44, 'Xixing Lu, Zhonglin Xu, Yu Yang', null);
INSERT INTO public.writers (id, name, photo) VALUES (45, 'Jo-Anne Brechin, Katharine McPhee', null);
INSERT INTO public.writers (id, name, photo) VALUES (46, 'Christopher Markus, Stephen McFeely, Stan Lee', null);
INSERT INTO public.writers (id, name, photo) VALUES (47, 'Shashank Khaitan, Ishita Moitra, Sumit Roy', null);
INSERT INTO public.writers (id, name, photo) VALUES (48, 'Hugo Cardozo', null);
INSERT INTO public.writers (id, name, photo) VALUES (49, 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens', null);
INSERT INTO public.writers (id, name, photo) VALUES (50, 'Michael Lesslie, Paul Wernick, Rhett Reese', null);
INSERT INTO public.writers (id, name, photo) VALUES (51, 'Sumit Arora, J.P. Dutta, Nidhi Dutta', null);
INSERT INTO public.writers (id, name, photo) VALUES (52, 'Meg LeFauve, Dave Holstein, Kelsey Mann', null);
INSERT INTO public.writers (id, name, photo) VALUES (53, 'Christophe Gans, Sandra Vo-Anh, William Josef Schneider', null);
INSERT INTO public.writers (id, name, photo) VALUES (54, 'Bong Joon Ho, Han Jin-won', null);
INSERT INTO public.writers (id, name, photo) VALUES (55, 'Emily Brontë, Emerald Fennell', null);
INSERT INTO public.writers (id, name, photo) VALUES (56, 'B.J. Novak', null);
INSERT INTO public.writers (id, name, photo) VALUES (57, 'Joseph Kosinski, Ehren Kruger', null);
INSERT INTO public.writers (id, name, photo) VALUES (58, 'James Cameron', null);
INSERT INTO public.writers (id, name, photo) VALUES (59, 'Kristoffer Borgli', null);
INSERT INTO public.writers (id, name, photo) VALUES (60, 'Abdulhakeem Hakeem', null);
INSERT INTO public.writers (id, name, photo) VALUES (62, 'Rebecca Sonnenshine, Freida McFadden', null);
INSERT INTO public.writers (id, name, photo) VALUES (61, 'Yavuz Turgul', null);
INSERT INTO public.writers (id, name, photo) VALUES (63, 'Drew Goddard, Andy Weir', null);
INSERT INTO public.writers (id, name, photo) VALUES (64, 'Phil Lord, Rodney Rothman', null);
INSERT INTO public.writers (id, name, photo) VALUES (65, 'Anna Greenfield', null);
INSERT INTO public.writers (id, name, photo) VALUES (66, 'Paul Thomas Anderson, Thomas Pynchon', null);
INSERT INTO public.writers (id, name, photo) VALUES (67, 'Byron Howard, Rich Moore, Jared Bush', null);
INSERT INTO public.writers (id, name, photo) VALUES (68, 'Matthew Fogel', null);
INSERT INTO public.writers (id, name, photo) VALUES (69, 'Hans Bauer, Jim Cash, Jack Epps Jr.', null);
INSERT INTO public.writers (id, name, photo) VALUES (70, 'Stephen Sommers', null);
INSERT INTO public.writers (id, name, photo) VALUES (71, 'Ronald Millar, George Froeschel', null);
INSERT INTO public.writers (id, name, photo) VALUES (72, 'Giuseppe Tornatore, Luciano Vincenzoni', null);
INSERT INTO public.writers (id, name, photo) VALUES (73, 'Henriette Jelinek, Jeanne Moreau', null);
INSERT INTO public.writers (id, name, photo) VALUES (74, 'Bram Stoker, James V. Hart', null);
INSERT INTO public.writers (id, name, photo) VALUES (75, 'James Cameron, Rick Jaffa, Amanda Silver', null);
INSERT INTO public.writers (id, name, photo) VALUES (76, 'Kin-Yee Au, Larry Yang, Nai-Hoi Yau', null);
INSERT INTO public.writers (id, name, photo) VALUES (77, 'Chloé Zhao, Maggie O''Farrell', null);
INSERT INTO public.writers (id, name, photo) VALUES (78, 'Andrew Stanton, Daniel Gerson, Pete Docter', null);
INSERT INTO public.writers (id, name, photo) VALUES (79, 'Mike White, Ken Daurio', null);
INSERT INTO public.writers (id, name, photo) VALUES (80, 'Winston Groom, Eric Roth', null);
INSERT INTO public.writers (id, name, photo) VALUES (81, 'Anna Todd, Sharon Soboil', null);
INSERT INTO public.writers (id, name, photo) VALUES (82, 'Anne-Marie Hess', null);
INSERT INTO public.writers (id, name, photo) VALUES (83, 'Joss Whedon, Zak Penn', null);
INSERT INTO public.writers (id, name, photo) VALUES (84, 'Daniel Chong, Jesse Andrews, Jordan Harrison', null);
INSERT INTO public.writers (id, name, photo) VALUES (85, 'Yu-Chu Chiang, Yen-Chiao Huang, Meng-Ju Shieh', null);
INSERT INTO public.writers (id, name, photo) VALUES (86, 'William Davies, Dean DeBlois, Chris Sanders', null);
INSERT INTO public.writers (id, name, photo) VALUES (87, 'Mario Puzo, Francis Ford Coppola', null);
INSERT INTO public.writers (id, name, photo) VALUES (88, 'Kelly Marcel, Tom Hardy, Todd McFarlane', null);
INSERT INTO public.writers (id, name, photo) VALUES (89, 'Michael Paul Girard', null);
INSERT INTO public.writers (id, name, photo) VALUES (90, 'Makoto Shinkai', null);
INSERT INTO public.writers (id, name, photo) VALUES (91, 'Jared Bush, Dana Ledoux Miller, Bek Smith', null);
INSERT INTO public.writers (id, name, photo) VALUES (92, 'Jonathan Tropper', null);
INSERT INTO public.writers (id, name, photo) VALUES (93, 'Bart Layton, Don Winslow', null);
INSERT INTO public.writers (id, name, photo) VALUES (94, 'Josh Friedman, David Koepp, H.G. Wells', null);
INSERT INTO public.writers (id, name, photo) VALUES (95, 'Mel Gibson, Farhad Safinia', null);
INSERT INTO public.writers (id, name, photo) VALUES (96, 'Bruce Geller, Christopher McQuarrie, Erik Jendresen', null);
INSERT INTO public.writers (id, name, photo) VALUES (97, 'David Koepp, Michael Crichton', null);
INSERT INTO public.writers (id, name, photo) VALUES (98, 'Winnie Holzman, Dana Fox, Gregory Maguire', null);
INSERT INTO public.writers (id, name, photo) VALUES (99, 'Umut Açikalin, Ferhat Ergün, Serhat Solmaz', null);
INSERT INTO public.writers (id, name, photo) VALUES (100, 'Stephen Sommers, Lloyd Fonvielle, Kevin Jarre', null);
INSERT INTO public.writers (id, name, photo) VALUES (101, 'Jonah Hill, Ezra Woods', null);
INSERT INTO public.writers (id, name, photo) VALUES (102, 'Jamie Powell', null);
INSERT INTO public.writers (id, name, photo) VALUES (103, 'Stephen King, Steven E. de Souza', null);
INSERT INTO public.writers (id, name, photo) VALUES (104, 'Justin Theroux, Stan Lee, Don Heck', null);
INSERT INTO public.writers (id, name, photo) VALUES (105, 'Stan Lee, Steve Ditko, David Koepp', null);
INSERT INTO public.writers (id, name, photo) VALUES (106, 'Ward Parry', null);
INSERT INTO public.writers (id, name, photo) VALUES (107, 'Chris McKenna, Erik Sommers, Stan Lee', null);
INSERT INTO public.writers (id, name, photo) VALUES (108, 'Peter Dexter, Jim Quinlan, Nora Ephron', null);
INSERT INTO public.writers (id, name, photo) VALUES (109, 'Quentin Tarantino, Roger Avary', null);
INSERT INTO public.writers (id, name, photo) VALUES (110, 'Guillermo del Toro, Mary Shelley', null);
INSERT INTO public.writers (id, name, photo) VALUES (111, 'Nikolay Lebedev, Aleksey Sidorov', null);
INSERT INTO public.writers (id, name, photo) VALUES (112, 'Jonathan Goldstein, John Francis Daley, Jon Watts', null);
INSERT INTO public.writers (id, name, photo) VALUES (113, 'Hayao Miyazaki', null);
INSERT INTO public.writers (id, name, photo) VALUES (114, 'Chris Sanders, Peter Brown', null);
INSERT INTO public.writers (id, name, photo) VALUES (115, 'Alan R. Cohen, Alan Freedland, Bryan Bertino', null);
INSERT INTO public.writers (id, name, photo) VALUES (117, 'Rich Wilkes', null);
INSERT INTO public.writers (id, name, photo) VALUES (116, 'Benedict Fitzgerald, Mel Gibson', null);
INSERT INTO public.writers (id, name, photo) VALUES (140, 'Ian Goldberg, Richard Naing, David Leslie Johnson-McGoldrick', null);
INSERT INTO public.writers (id, name, photo) VALUES (148, 'Aditya Dhar', null);
INSERT INTO public.writers (id, name, photo) VALUES (118, 'Patrick Hughes, James Beaufort', null);
INSERT INTO public.writers (id, name, photo) VALUES (120, 'Gege Akutami, Hiroshi Seko', null);
INSERT INTO public.writers (id, name, photo) VALUES (128, 'Guy Busick, R. Christopher Murphy', null);
INSERT INTO public.writers (id, name, photo) VALUES (131, 'Jimmy Fowlie, Ceara O''Sullivan', null);
INSERT INTO public.writers (id, name, photo) VALUES (134, 'Danya Jimenez, Hannah McMechan, Maggie Kang', null);
INSERT INTO public.writers (id, name, photo) VALUES (135, 'Henry Selick, Neil Gaiman', null);
INSERT INTO public.writers (id, name, photo) VALUES (143, 'Marco van Belle', null);
INSERT INTO public.writers (id, name, photo) VALUES (146, 'Kotake Create, Kentaro Hirase, Genki Kawamura', null);
INSERT INTO public.writers (id, name, photo) VALUES (147, 'Jared Bush', null);
INSERT INTO public.writers (id, name, photo) VALUES (152, 'Matthew Robinson', null);
INSERT INTO public.writers (id, name, photo) VALUES (153, 'Phil Lord, Christopher Miller, Dave Callaham', null);
INSERT INTO public.writers (id, name, photo) VALUES (119, 'Joss Whedon, Andrew Stanton, Joel Cohen', null);
INSERT INTO public.writers (id, name, photo) VALUES (133, 'Jean-Paul Bathany, Olivier Ducray, Wilfried Méance', null);
INSERT INTO public.writers (id, name, photo) VALUES (142, 'Nicholas Pileggi, Martin Scorsese', null);
INSERT INTO public.writers (id, name, photo) VALUES (150, 'Hampton Fancher, Michael Green, Philip K. Dick', null);
INSERT INTO public.writers (id, name, photo) VALUES (121, 'Ehren Kruger, Eric Warren Singer, Christopher McQuarrie', null);
INSERT INTO public.writers (id, name, photo) VALUES (125, 'Brent Dawes, Kyle Portbury, Sam Wilson', null);
INSERT INTO public.writers (id, name, photo) VALUES (127, 'Johannes Roberts, Ernest Riera', null);
INSERT INTO public.writers (id, name, photo) VALUES (130, 'Chuck Palahniuk, Jim Uhls', null);
INSERT INTO public.writers (id, name, photo) VALUES (136, 'Scott Cawthon', null);
INSERT INTO public.writers (id, name, photo) VALUES (138, 'Christina Chang, Daniel Chong, Alexandra Chiu', null);
INSERT INTO public.writers (id, name, photo) VALUES (144, 'Jalmari Helander', null);
INSERT INTO public.writers (id, name, photo) VALUES (145, 'Charlie Kaufman, Michel Gondry, Pierre Bismuth', null);
INSERT INTO public.writers (id, name, photo) VALUES (151, 'Chris Bowman, Hubbel Palmer, Neil Widener', null);
INSERT INTO public.writers (id, name, photo) VALUES (122, 'Christopher Nolan', null);
INSERT INTO public.writers (id, name, photo) VALUES (124, 'Francis Ford Coppola, Mario Puzo', null);
INSERT INTO public.writers (id, name, photo) VALUES (126, 'Andrew Kevin Walker', null);
INSERT INTO public.writers (id, name, photo) VALUES (132, 'Lauren Levine, Colleen Hoover', null);
INSERT INTO public.writers (id, name, photo) VALUES (139, 'Mario Gariazzo, Fernando Di Leo', null);
INSERT INTO public.writers (id, name, photo) VALUES (141, 'Piero Regnoli', null);
INSERT INTO public.writers (id, name, photo) VALUES (149, 'Alex Garland', null);
INSERT INTO public.writers (id, name, photo) VALUES (154, 'Olivier Nakache, Éric Toledano, Philippe Pozzo di Borgo', null);
INSERT INTO public.writers (id, name, photo) VALUES (123, 'Aaron Buchsbaum, Teddy Riley, Nicolas Curcio', null);
INSERT INTO public.writers (id, name, photo) VALUES (129, 'Richard Nielsen', null);
INSERT INTO public.writers (id, name, photo) VALUES (137, 'Tommy Wirkola', null);
INSERT INTO public.writers (id, name, photo) VALUES (155, 'Kate Freund', null);
